name       : libmemcached
version    : 1.0.18
release    : 1
source     :
    - https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz : e22c0bb032fde08f53de9ffbc5a128233041d9f33b5de022c0978a2149885f82
license    : BSD-3-Clause
component  : programming
summary    : A library in C for connecting to memcached servers
description: |
    A library in C for connecting to memcached servers
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
